### ISSUE TITLE
Additional Configuration Options for Jupiter Terminal Settings Modal

### ISSUE THREAD

**Issue by kizmt** [jup-ag/terminal#123]
# Feature Request: Additional Configuration Options for Jupiter Terminal Settings Modal

## Overview
Request to expose additional configuration options (priority fees and dynamic slippage) in the IInit interface when using Jupiter Terminal.

## Current Type Definition
Currently, the IInit interface handles slippage configuration like this:

```
export interface IInit {
// ... other props
formProps?: FormProps;
/** Use user's slippage instead of initialSlippageBps, defaults to true */
useUserSlippage?: boolean;
/** TODO: NOT Supported yet, presets of slippages, defaults to [0.1, 0.5, 1.0] */
slippagePresets?: number[];
// ... other props
}
```

## Desired Type Definitions
Would like to extend FormProps to include:

```
export interface IInit {
// Existing props...
formProps?: FormProps;
useUserSlippage?: boolean;
slippagePresets?: number[];
// New configuration options
useDynamicSlippage?: boolean;
maxDynamicSlippageBps?: number;
defaultSlippageMode?: "DYNAMIC" | "FIXED";
// Priority fee configuration
usePriorityFees?: boolean;
defaultPriorityFee?: number;
defaultPriorityMode?: "MAX" | "EXACT";
defaultPriorityLevel?: "FAST" | "TURBO" | "ULTRA";
}
```

## Use Cases
1. Need to set higher priority fee levels by default for better transaction reliability
2. Want to start users with Turbo/Ultra mode enabled to ensure faster transaction processing
3. Need to set maximum dynamic slippage limits for user protection

## Current Workarounds
Currently unable to configure these settings during initialization, forcing users to manually adjust settings after the terminal loads.

## Questions
1. Would these be better as top-level IInit properties or should they be nested under a new config object?
2. Are there plans to expose more configuration options for the NPM package?

Let me know if you need any additional information!

**Comment by KoenRijpstra** [comment]
@worlddlckgh gm! Could you take a look at this? We’re planning to integrate swapping into the new XRAY explorer and want to ensure users have an optimal swapping experience by default. Let me know if you need more information or have any questions. Greetings from the Helius team!

**Comment by worlddlckgh** [comment]
https://github.com/jup-ag/terminal/issues/123
PR available here for testing

**Comment by kizmt** [comment]
closing as this has been resolved in PR https://github.com/jup-ag/terminal/pull/129
