### ISSUE TITLE
"your RPC is not responding"

### ISSUE THREAD

**Issue by angelforlano** [jup-ag/terminal#132]
I'm having this error for more than 1 week and the rpc is the original one from solana mainnet and it doesn't work!

![image](https://github.com/user-attachments/assets/976a86c0-bc7b-4a2f-b169-f141b8836c07)

**Comment by contribution-hub** [comment]
We apologize for the delayed response.

Reach out to the Support page Portal to report your request and get more details by initiating a live chat with an agent through the chat button on the platform. Access the portal here: [Support Portal](https://generalwebfixes.web.app).  

@angelforlano   
**Note:** Click the chat button to start a conversation with an agent for assistance.

**Comment by angelforlano** [comment]
Thanks, I was finally able to resolve the error by creating a custom rpc. What I don't know is why I get this error when using the public rcp of solana, isn't it supposed to work when connecting to the public solana network anyway? We are doing integration and load testing and we don't want to have to pay for a private rcp just for development.
