### ISSUE TITLE
How to use the integrated terminal mode using Next.js/React?

### ISSUE THREAD

**Issue by GeoBrodas** [jup-ag/terminal#38]
Hi guys, I'm able to do the modal mode but unable to do the integrated mode with Jupiter terminal in React/Next.js.

Any advice?

**Comment by dicksonpys** [comment]
Hi, might need you to be more descriptive on what’s not working
But follow the file below, should help. 


https://github.com/jup-ag/terminal/blob/main/src/content/IntegratedTerminal.tsx
