### ISSUE TITLE
Input (.) into InputMint crashes the swap ui

### ISSUE THREAD

**Issue by thekesslereffect** [jup-ag/terminal#65]
When you press . instead of 0.# the ui crashes.

**Comment by thekesslereffect** [comment]
In case you don't understand what I mean: **If you input a period first**, instead of 0 then period, it will crash the ui.

![image](https://github.com/jup-ag/terminal/assets/24286691/29d59dc1-6417-4455-8784-497e950cbe1f)
![image](https://github.com/jup-ag/terminal/assets/24286691/7d06dd5b-e3c5-48aa-8ed6-c4ec0bbf36be)

**Comment by thekesslereffect** [comment]
Also the bottom token displays Lamports instead of SOL for my mint address ( CErSpNnEHUNsNw3AZJhyvekwhMpr9H3W2S71uA3pzJus ) . So that's a bit confusing.

**Comment by worlddlckgh** [comment]
Decimals issue are fixed on version 2.3.0
https://github.com/jup-ag/terminal/pull/74

**Comment by worlddlckgh** [comment]
> Also the bottom token displays Lamports instead of SOL for my mint address ( CErSpNnEHUNsNw3AZJhyvekwhMpr9H3W2S71uA3pzJus ) . So that's a bit confusing.

can you clarify on this?
