### ISSUE TITLE
Rounding issue with tiny numbers

### ISSUE THREAD

**Issue by NotoriousPyro** [jup-ag/terminal#72]
Image pretty much explains it, but when you have a very small amount of something and click MAX, it is rounding it to a much larger number... so `0.00000026` is being round to `2.67` which is out by roughly `~10⁷`

![image](https://github.com/jup-ag/terminal/assets/706132/bca8e5e6-b1b8-4be4-8b61-8efa31f9c32c)

**Comment by worlddlckgh** [comment]
https://github.com/jup-ag/terminal/pull/82
This PR should fix that

**Comment by NotoriousPyro** [comment]
Doesn't seem to be fixed...
![image](https://github.com/jup-ag/terminal/assets/706132/d5d0aabc-49d0-4c21-ab58-b36ebaf63396)

**Comment by NotoriousPyro** [comment]
As soon as `toFixed` is called, the precision is lost... the only way to do it is use strings and BigNumbers/Decimal. The field would have to be changed to a string field...
