### ISSUE TITLE
fetchAllMints getting called several times

### ISSUE THREAD

**Issue by llegoelkelo** [jup-ag/terminal#73]
`fetchAllMints` is getting executed several times when calling `window.Jupiter.init`. The amount of times that `fetchAllMints` is called increases every time one calls `window.Jupiter.init`.

This effect is the culprit: https://github.com/jup-ag/terminal/blob/main/src/contexts/TokenContextProvider.tsx#L55

**Comment by worlddlckgh** [comment]
Initially tried to use `useQuery` to achieve caching effect for
- page reload/refresh
- window.Jupiter.init()

but to no avail, this PR https://github.com/jup-ag/terminal/pull/83 we ship a simpler local storage caching solution that is inline with our FE 10 minutes caching as well
