### ISSUE TITLE
Jupiter Terminal V3 CSS overrides global page styles 

### ISSUE THREAD

**Issue by llegoelkelo** [jup-ag/terminal#90]
Hey guys, when loading `https://terminal.jup.ag/main-v3.js` the css file `https://terminal.jup.ag/main-3.0.0-Jupiter.css` eventually also gets loaded into our dapp but it actually overrides some styles.

So far I have only noticed our buttons being affected but it could be more:

<img width="320" alt="image" src="https://github.com/jup-ag/terminal/assets/160888776/4fc00814-eb06-48c2-9a2d-11ed147f2354">

**Comment by llegoelkelo** [comment]
You can actually see this in there kitchen sink page as well: https://terminal.jup.ag

**Comment by llegoelkelo** [comment]
Turns out this was simply a css injection order. I have submitted a PR.

**Comment by llegoelkelo** [comment]
I still have this issue even after #94 was merged and deployed.

**Comment by TechTronixx** [comment]
Yep , Just tested & it still persists.

**Comment by llegoelkelo** [comment]
maybe I tested too quickly after launch because it definitely works now. Closing. Thanks @worlddlckgh
